### ISSUE TITLE
Pin event

### ISSUE THREAD

**Issue by CoverJ** [InkedCurtis/FUT18-WebApp-Connector#1]
Hey mate,

I'm not very good at php so wouldn't be using this script but I couldn't see any pin-river requests and this year it looks like you need one before you login.

Just thought I'd extend a warning to yourself and others but like I said I know next to nothing about php and could be wrong about the whole thing.

**Comment by InkedCurtis** [comment]
Hey,

Yeah pinEvents is needed but it's just a simple login process mimic, I don't intend on people to use this for anything other than educational needs on learning how the login performs.
